# WARNING: This is a DEVELOPMENT docker-compose file, it should not be used for production.
version: "3"
services:
  app:
    build: .
    restart: always
    ports:
      - 80:80
      - 3000:3000
      - 443:443
    environment:
      - NODE_ENV=development
    volumes:
      - ./data:/data
      - ./data/letsencrypt:/etc/letsencrypt
